const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.Rotate,
		C3.Plugins.Particles,
		C3.Plugins.Touch,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.TiledBg,
		C3.Plugins.Arr,
		C3.Plugins.LocalStorage,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.TiledBg.Acts.SetTowardPosition,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.Text.Acts.SetSize,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue
	];
};
self.C3_JsPropNameTable = [
	{LastX: 0},
	{LastY: 0},
	{ThunderAngle: 0},
	{Skins: 0},
	{Physics: 0},
	{Rotate: 0},
	{Thorn: 0},
	{Solid: 0},
	{Balloon: 0},
	{Splash: 0},
	{Particles: 0},
	{Particles2: 0},
	{Particles3: 0},
	{Particles4: 0},
	{CatapultBlock: 0},
	{Touch: 0},
	{Tween: 0},
	{BallTrail: 0},
	{ParticlesFail: 0},
	{CatapultRope: 0},
	{Particles5: 0},
	{Particles6: 0},
	{Particles7: 0},
	{Particles8: 0},
	{Particles9: 0},
	{Particles10: 0},
	{Particles11: 0},
	{Particles12: 0},
	{SoundButton: 0},
	{Back: 0},
	{LeftButton: 0},
	{RightButton: 0},
	{Version: 0},
	{Sine: 0},
	{Title: 0},
	{PlayButton: 0},
	{Level: 0},
	{LevelButton: 0},
	{Audio: 0},
	{Completed_fail: 0},
	{Emoji: 0},
	{Next: 0},
	{Shadow: 0},
	{Ray: 0},
	{ConfettiRed: 0},
	{ConfettiOrange: 0},
	{ConfettiYellow: 0},
	{ConfettiLightgreen: 0},
	{ConfettiGreen: 0},
	{ConfettiLightblue: 0},
	{ConfettiDarkblue: 0},
	{ConfettiPurple: 0},
	{ConfettiPink: 0},
	{Number: 0},
	{SaveGame: 0},
	{LocalStorage: 0},
	{Browser: 0},
	{Pics: 0},
	{Cursor: 0},
	{DistanceRuler: 0},
	{Platform: 0},
	{ParticlesGravity: 0},
	{Arrow: 0},
	{Obstacle: 0},
	{Restart: 0},
	{GravitySolid: 0},
	{txt: 0},
	{TiledBackground: 0},
	{HomeRestart: 0},
	{Board: 0},
	{TextLevels: 0},
	{Balloon2: 0},
	{Like: 0},
	{Balloons: 0},
	{FamilyParticles: 0},
	{IsAiming: 0},
	{Complete: 0},
	{BallUID: 0},
	{swipe: 0}
];

self.InstanceType = {
	Thorn: class extends self.ISpriteInstance {},
	Solid: class extends self.ISpriteInstance {},
	Balloon: class extends self.ISpriteInstance {},
	Splash: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Particles4: class extends self.IParticlesInstance {},
	CatapultBlock: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	BallTrail: class extends self.ISpriteInstance {},
	ParticlesFail: class extends self.IParticlesInstance {},
	CatapultRope: class extends self.ISpriteInstance {},
	Particles5: class extends self.IParticlesInstance {},
	Particles6: class extends self.IParticlesInstance {},
	Particles7: class extends self.IParticlesInstance {},
	Particles8: class extends self.IParticlesInstance {},
	Particles9: class extends self.IParticlesInstance {},
	Particles10: class extends self.IParticlesInstance {},
	Particles11: class extends self.IParticlesInstance {},
	Particles12: class extends self.IParticlesInstance {},
	SoundButton: class extends self.ISpriteInstance {},
	Back: class extends self.ISpriteInstance {},
	LeftButton: class extends self.ISpriteInstance {},
	RightButton: class extends self.ISpriteInstance {},
	Version: class extends self.ITextInstance {},
	Title: class extends self.ISpriteInstance {},
	PlayButton: class extends self.ISpriteInstance {},
	LevelButton: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Completed_fail: class extends self.ISpriteInstance {},
	Emoji: class extends self.ISpriteInstance {},
	Next: class extends self.ISpriteInstance {},
	Shadow: class extends self.ITiledBackgroundInstance {},
	Ray: class extends self.ISpriteInstance {},
	ConfettiRed: class extends self.IParticlesInstance {},
	ConfettiOrange: class extends self.IParticlesInstance {},
	ConfettiYellow: class extends self.IParticlesInstance {},
	ConfettiLightgreen: class extends self.IParticlesInstance {},
	ConfettiGreen: class extends self.IParticlesInstance {},
	ConfettiLightblue: class extends self.IParticlesInstance {},
	ConfettiDarkblue: class extends self.IParticlesInstance {},
	ConfettiPurple: class extends self.IParticlesInstance {},
	ConfettiPink: class extends self.IParticlesInstance {},
	Number: class extends self.ITextInstance {},
	SaveGame: class extends self.IArrayInstance {},
	LocalStorage: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Pics: class extends self.ISpriteInstance {},
	Cursor: class extends self.ISpriteInstance {},
	DistanceRuler: class extends self.ITiledBackgroundInstance {},
	Platform: class extends self.ISpriteInstance {},
	ParticlesGravity: class extends self.IParticlesInstance {},
	Arrow: class extends self.ISpriteInstance {},
	Obstacle: class extends self.ISpriteInstance {},
	Restart: class extends self.ISpriteInstance {},
	GravitySolid: class extends self.ISpriteInstance {},
	txt: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	HomeRestart: class extends self.ISpriteInstance {},
	Board: class extends self.ISpriteInstance {},
	TextLevels: class extends self.ITextInstance {},
	Balloon2: class extends self.ISpriteInstance {},
	Like: class extends self.ISpriteInstance {},
	Balloons: class extends self.ISpriteInstance {},
	FamilyParticles: class extends self.IParticlesInstance {}
}